name: Deploy Prod

on:
  push:
    branches:
      - master
     
jobs:
  deploy:
    name: Deploy Prod
    uses: bancodebogota/bbog-dt-pipeline/.github/workflows/deploy_angular_frontend.yml@v0.1.52
    with:
      project-name: "bbog-tcc-ldf-cargue-facturas-web-ui"
      app-name: "bbog-tcc-ldf-cargue-facturas-web-ui"
      version: $(node -p "require('./package.json').version")
      aws-region: us-east-1
      build-folder: "dist"
      bucket: "pr-bbog-tcc"
      distribution-id: "E2FKJHOEXCVNIW" 
      enable-custom-app-name: false
      node-version: "14.x"
      build-command: "npm run build:prod"
      environment: pr
    secrets:
      DIG_READER_GITHUB_ACCESS_TOKEN: ${{ secrets.DIG_READER_GITHUB_ACCESS_TOKEN }}
      ARTIFACTORY_READER_USER: ${{ secrets.ARTIFACTORY_READER_USER }}
      ARTIFACTORY_READER_API_KEY: ${{ secrets.ARTIFACTORY_READER_API_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ROLE_DEPLOY_FRONTEND: ${{ secrets.AWS_ROLE_DEPLOY_FRONTEND }}